#! /bin/tcsh
#
# Use this to regenerate a self-signed certificate when the current one
# expires. 
#
rm pdbkeys
keytool -genkey -alias RCSB-PDB -keypass pdb0922 -keystore pdbkeys -storepass pdb0922 -dname "cn=Peter Rose, ou=PDB o=RCSB, c=US" -keystore pdbkeys
keytool -selfcert -alias RCSB-PDB -keypass pdb0922 -dname "cn=Peter Rose, o=RCSB, c=US" -keystore pdbkeys -storepass pdb0922
