<?php
  session_start();
  set_include_path($_SESSION['INCLUDE_PATH']);
  include_once "resources/snippets/prefix.php";
?>
	  <ul class="preface">
	    <li>
	      In the <em>.pdb</em> loader, CONECT records are ignored.  Bonds are determined either through
	      a dictionary lookup, or via calculation if the lookup fails.
	    </li>
	    <li>
	      Currently the lookup files described here are generated by an external process and are incorporated
	      directly within the 'Structure Models' jar as a resource.  This means that they can only be updated
	      if the 'Structure Models' jar is updated.
	    </li>
	    <li class="follow-on">
	      A preferable approach would be to put them in their own jar, that can be updated independently
	      of the model jar (or any functional jars.)
	    </li>
	    <li class="follow-on">
	      See the <em>RCSB Excluded</em> project, <em>CL Tools</em> directory for more information.</p>
	    </li>
	  </ul>
	  <ul class="relevent-classes">
	    <li>ChemicalComponentBonds</li>
	    <li>NucleicAcidInfo</li>
	  </ul>
	</p>
    <p>
      MBT maintains a dictionary of known structures. This comes from a combined .cif file that is found at this ftp
      site:
    </p>
    <code><a href="ftp://ftp.wwpdb.org/pub/pdb/data/monomers/components.cif.gz">
    	ftp://ftp.wwpdb.org/pub/pdb/data/monomers/components.cif.gz</a>
    </code>
    <p>
      This file is loaded and broken apart by an external process - see the 'RCSB Excluded' project, package
      'org.rcsb.pw.tools' package.
    </p>
    <p>
      'ChemicalComponentBondsCreator' is run from the commandline against the file. It's not a full parser - it just
      extracts bond information. The output of that (ChemicalComponentBonds.dat') is copied into the 'RCSB MBT Libs'
      project, source directory 'Structure Model', in the package 'org.rcsb.mbt.model.util' as a resource.
    </p>
    <p>
      At runtime, this abbreviated file is picked up and put into a hash-table. Atoms are checked against this for bond
      information.
    </p>
    <p>
      If bonds are not found for a given residue, the atoms are run through a bond-generation algorithm that determines
      bonds by distance. Atoms are arranged in an octree, first, for quick spatial checks. I don't think this is
      working correctly, right now. But, it's in there.
    </p>
    <p>
      Look in the 'RCSB MBT Libs' project, source directory 'Structure Model', in the package 'org.rcsb.mbt.model' for
      the StructureMap class, again. In there, find 'generateBonds()'. Note it checks a flag to ignore the dictionary
      lookup and strictly use the distance algorithm (suspect this is for debugging, mainly). The
      'org.rcsb.mbt.model.BondFactory' class is what does the dictionary lookup or bond calculations, depending on
      what's required.
    </p>
    <p>
      Incidentally, the same kind of mechanism is used to determined nucleic acid classification. In the 'RCSB
      Excluded' project, source directory 'CL Tools', the 'org.rcsb.pw.tools.FindAllNucleicAcidCompoundNames' is also
      run from the commandline and generates an output file ('NucleicAcidCompoundNameMapCreator.txt'). In this case,
      the transferance mechanism is a bit different: it generates a code snippet that is pasted into
      'org.rcsb.mbt.model.util.NucleicAcidInfo.java' , where it is incorporated into a lookup set.
    </p>
<?php
  include_once "resources/snippets/suffix.php";
?>

